/**
 * Created by JP on 2017/2/8.
 */

export const LOAD_README_REQUEST = 'LOAD_README_REQUEST'
export const LOAD_README_SUCCESS = 'LOAD_README_SUCCESS'
export const LOAD_README_ERROR = 'LOAD_README_ERROR'
