/**
 * Created by JP on 2017/2/8.
 */

export const LOAD_TODO_LIST_REQUEST = 'LOAD_TODO_LIST_REQUEST'
export const LOAD_TODO_LIST_SUCCESS = 'LOAD_TODO_LIST_SUCCESS'
export const LOAD_TODO_LIST_ERROR = 'LOAD_TODO_LIST_ERROR'
